= {product_name} 

:page-tag: starlight-kafka,dev,admin,pulsar,kafka

{product_name} brings the native Apache Kafka protocol support to Apache Pulsar by introducing a Kafka protocol handler on Pulsar brokers. By adding the {product_name} protocol handler to your existing Pulsar cluster, you can migrate your existing Kafka applications and services to Pulsar without modifying the code. This enables Kafka applications to leverage Pulsar’s powerful features, such as:

- Streamlined operations with enterprise-grade multi-tenancy
- Simplified operations with a rebalance-free architecture
- Infinite event stream retention with Apache BookKeeper and tiered storage
- Serverless event processing with Pulsar Functions

{product_name}, implemented as a Pulsar https://github.com/apache/pulsar/blob/master/pulsar-broker/src/main/java/org/apache/pulsar/broker/protocol/ProtocolHandler.java[protocol handler] plugin with the protocol name "kafka", is loaded when Pulsar broker starts. It helps reduce the barriers for people adopting Pulsar to achieve their business success by providing a native Kafka protocol support on Apache Pulsar. By integrating the two popular event streaming ecosystems, {product_name} unlocks new use cases. To accelerate your development of real-time applications and services, you can leverage these advantages from each ecosystem and build a truly unified event streaming platform with Apache Pulsar.

{product_name} implements the Kafka wire protocol on Pulsar by leveraging the existing components (such as topic discovery, the distributed log library - ManagedLedger, cursors and so on) that Pulsar already has.

== Features 

{product_name} adds additional features to make native Kafka protocol support even better.

* xref:starlight-kafka-schema-registry.adoc[Schema registry] - A schema registry compatible with both the https://docs.confluent.io/platform/current/schema-registry/index.html[Confluent Schema Registry®] and the https://www.apicur.io/registry[Apicurio Schema Registry]. +

* xref:starlight-kafka-proxy.adoc[Proxy extension] - allows the Kafka client to access your Pulsar cluster the same way as Pulsar clients do. +

* Integrated support for the Pulsar schema registry. +
//* xref:starlight-cdc.adoc[AVRO consumption] - consume AVRO schema from a Kafka client. 

== What's next?

* xref:starlight-kafka-quickstart.adoc[{product_name} Quickstart]
* xref:starlight-kafka-implementation.adoc[{product_name} Implementation] 
