= Install the {product} extension
:navtitle: Installation

This guide explains how to install the {product} extension as a protocol handler, and then use it to produce and consume {kafka-reg} messages on a {pulsar-reg} cluster.

To install {product} as a proxy extension, see xref:operations:starlight-kafka-proxy.adoc[].

[#prerequisites]
== Prerequisites

To use {product}, you need a {pulsar-short} cluster from {astra-stream}, {luna-streaming}, or a self-managed or standalone {pulsar-short} deployment.

{product} version 2.10 is compatible with the following:

* {pulsar-short} version 2.10.x
* {kafka-short} client versions 0.10, 1.x, 2.x, and 3.x
* {kafka-short} Streams
* {kafka-short} CLI

{product} requires JDK 11.

[#establish-the-kafka-protocol-handler]
== Establish the {kafka-short} protocol handler

Before a {kafka-short} client can interact with your {pulsar-short} cluster, you need the {product} protocol handler installed in the cluster.

[tabs]
======
{astra-stream}::
+
--
These steps explain how to enable the {product} protocol handler in an {astra-stream} {pulsar-short} cluster, and then get the connection details for your {kafka-short} client:

. In the {astra-ui-link} header, click icon:grip[name="Applications"], and then select *Streaming*.

. xref:astra-streaming:getting-started:index.adoc[Create a tenant] or click the name of an existing tenant.

. Go to your tenant's **Connect** tab, select **{kafka-short}**, and then click **Enable {kafka-short}**.

. Review the information about the {product} extension, and then click **Enable {kafka-short}** to confirm that you want to enable this extension on your tenant.
+
[IMPORTANT]
====
This action creates a configuration file and the following three namespaces in your {astra-stream} tenant automatically:

* `kafka`: Produces and consumes messages
* `+__kafka+`: Supports required {kafka-short} functionality
* `+__kafka_unlimited+`: Stores metadata

These namespaces are required for the {product} extension to function properly.
These are permanent namespaces that cannot be removed except by deleting the entire tenant and all of its data.
====

. Save the {kafka-short} connection details to a file named `ssl.properties`.
The actual values depend on your {astra-stream} tenant's configuration and cloud provider.
+
.ssl.properties
[source,plain,subs="+quotes,+attributes"]
----
username: **TENANT_NAME**
password: token:{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}{asterisk}
bootstrap.servers: kafka-**PROVIDER**-**REGION**.streaming.datastax.com:9093
schema.registry.url: https://kafka-**PROVIDER**-**REGION**.streaming.datastax.com:8081
security.protocol: SASL_SSL
sasl.mechanism: PLAIN
----
+
[TIP]
====
In {astra-stream}, if you click icon:download[name="Download"] or icon:clipboard[name="Copy"], then a {pulsar-short} token is included in the `password` field automatically.
You can also generate a token on your tenant's **Settings** tab.
====

. Optional: Add a session timeout value to the `ssl.properties` file to avoid connection issues with some {kafka-short} clients:
+
[source,properties]
----
session.timeout.ms=45000
----
+
Continue to the next section to learn how to use the connection details in a {kafka-short} client script.
--

{luna-streaming}::
+
--
The {product} extension is included in the `luna-streaming-all` image used to deploy an {luna-streaming} cluster (formerly DataStax Luna Streaming).
The {company} {pulsar-short} Helm chart simplifies deployment of the {kafka-short} extension.

The following steps explain how to deploy a {company} {pulsar-short} Helm chart to create a simple {pulsar-short} cluster with the {product} extension ready to use.

. Make sure you meet the following prerequisites:
+
* Install https://helm.sh/docs/intro/install/[Helm 3 CLI] version 3.8.0 or later.
* Install https://www.apache.org/dyn/closer.cgi?path=/kafka/3.3.1/kafka_2.13-3.3.1.tgz[{kafka-short} CLI] version 3.3.1 or later
* Install https://kubernetes.io/docs/tasks/tools/[kubectl CLI] version 1.23.4 or later.
* Have access to a Kubernetes cluster with permission to create a namespace, deployments, and pods.

. Add the {company} {pulsar-short} Helm chart repo to your Helm store:
+
[source,shell]
----
helm repo add datastax-pulsar https://datastax.github.io/pulsar-helm-chart
----
+
[IMPORTANT]
====
The https://datastax.github.io/pulsar-helm-chart[{company} {pulsar-short} Helm chart] is deprecated.
For Kubernetes deployments, {company} recommends xref:kaap-operator::index.adoc[{kaap}].
====

. Install the Helm chart using a xref:installation:attachment$values.yaml[minimal values file].
The following command creates a Helm release named `my-pulsar-cluster` using the {company} {pulsar-short} Helm chart within a Kubernetes namespace named `datastax-pulsar`.
This minimal configuration creates only the essential components and has no ingress or load balanced services.
+
[source,shell]
----
helm install \
  --namespace datastax-pulsar \
  --create-namespace \
  --values path/to/values.yaml \
  --version 3.0.4 \
  my-pulsar-cluster \
  datastax-pulsar/pulsar
----

. Wait for the broker pod to reach a running state.
It might restart a few times while the components start up.
+
[source,shell]
----
kubectl -n datastax-pulsar wait --for=condition=Ready pod/pulsar-broker-0 --timeout=120s
----

. Use the {pulsar-short} Admin CLI to inspect the tenants, namespaces, and topics that were created in your {pulsar-short} cluster when you deployed the Helm chart with the {product} extension enabled.
+
By default, the Helm chart create a tenant named `public` with a namespace named `default`.
In addition, the {product} extension creates several namespaces and topics that are required for its functionality.
These namespaces are prefixed with `+__kafka+`.
+
List the namespaces in the `public` tenant:
+
[source,shell]
----
~/apache-pulsar-3.1.3$ ./bin/pulsar-admin namespaces list public
----
+
Make sure the output includes the `default` and `+__kafka+` namespaces:
+
[source,shell]
----
public/__kafka
public/__kafka_producerid
public/default
----

. Enable port forwarding for the {pulsar-short} Admin and {product} services that are running on the Kubernetes cluster:
+
.. In a new terminal, port forward the {pulsar-short} Admin service:
+
[source,shell]
----
kubectl port-forward -n datastax-pulsar service/pulsar-broker 8080:8080
----

.. In a separate terminal window, port forward the {product} service:
+
[source,shell]
----
kubectl port-forward -n datastax-pulsar service/pulsar-proxy 9092:9092
----

+
[TIP]
====
You don't need to open the {pulsar-short} binary port to accept new messages when using {product}.
This is because {kafka-short} clients communicate using the {kafka-short} protocol on port 9092, which is handled by the {product} extension.
====
After deploying the Helm chart and enabling port forwarding, your applications can communicate with {pulsar-short} as if it were a real {kafka-short} host, as explained in the next section.
--

Self-managed::
+
--
. If this is the first time you've used protocol handlers with your {pulsar-short} deployment, create a `protocols` folder in the root of your {pulsar-short} directory.

. Download the `pulsar-protocol-handler-kafka-**VERSION**.nar` from the {product-repo}/releases[{product} GitHub repository].

. Copy the `.nar` file to your `pulsar/protocols` directory.

include::ROOT:partial$self-managed-config.adoc[]
--

Build from source::
+
--
Build the protocol handler from source if you want to customize the code or contribute to the project.

. Clone the {product} GitHub repository to your local machine:
+
[source,bash]
----
git clone https://github.com/datastax/starlight-for-kafka.git
----

. Change to the local repository directory:
+
[source,bash]
----
cd starlight-for-kafka
----

. If needed, set `jenv global 11` to use JDK 11 because {product} requires JDK11.

. Build the Maven project:
+
[source,java]
----
mvn clean install -DskipTests
----

. If this is the first time you've used protocol handlers with your {pulsar-short} deployment, create a `protocols` folder in the root of your {pulsar-short} directory.

. Copy the protocol handler `.nar` file to your {pulsar-short} `protocols` directory.
After building the project, the `.nar` file is available at `starlight-for-kafka/kafka-impl/target/pulsar-protocol-handler-kafka-**VERSION**.nar`.

include::ROOT:partial$self-managed-config.adoc[]
--
======

[#produce-and-consume-messages-with-starlight-for-kafka]
== Produce and consume messages with {product}

This section explains how to use your {pulsar-short} tenant's connection details with a {kafka-short} client to produce and consume messages with {product}.

{product} supports many different use cases.
With a {pulsar-short} cluster between publishers and consumers, you can change the type of publisher and consumer to fit your needs.

[TIP]
====
The {astra-stream} examples can be modified for {luna-streaming} and self-managed {pulsar-short} clusters by replacing the connection details with those for your cluster.
====

[tabs]
======
{astra-stream}::
+
--
[tabs]
====
{kafka-short} CLI::
+
This example uses command line tools included with the https://kafka.apache.org/downloads[{kafka} tarball].
+
. Enable {product} and get the `ssl.properties` connection details, as explained in <<establish-the-kafka-protocol-handler>>.
+
. In {astra-stream}, in the `kafka` namespace, create a topic to receive messages from the `kafka-console-producer`.
You can use any valid name for the topic.
+
. Move your {astra-stream} `ssl.properties` file into your {kafka-short} installation's `config` subdirectory, such as `kafka_2.13-3.1.0/config`.
+
. In a terminal window, use the `kafka-console-producer` tool to create a {kafka-short} producer that produces messages on the topic you created in the `kafka` namespace:
+
[source,shell,subs="+quotes"]
----
bin/kafka-console-producer \
--broker-list kafka-**PROVIDER**-**REGION**.streaming.datastax.com:9093 \
--topic **TENANT_NAME**/kafka/**TOPIC_NAME** \
--producer.config config/ssl.properties
----
+
When the producer is ready, it accepts standard input from the user.
To send a message, type it in the terminal, and then press kbd:[Return].
Optionally, you can send some messages before starting the consumer to see how it retrieves past messages.
+
. In a new terminal window, use the `kafka-console-consumer` tool to create a {kafka-short} consumer that consumes messages from the beginning of your topic:
+
[source,shell,subs="+quotes"]
----
bin/kafka-console-consumer \
--bootstrap-server kafka-**PROVIDER**-**REGION**.streaming.datastax.com:9093 \
--topic **TENANT_NAME**/kafka/**TOPIC_NAME** \
--consumer.config config/ssl.properties \
--from-beginning
----
+
Because this command uses the `--from-beginning` option, when the consumer starts, it retrieves any messages that were sent to the topic before it started.
+
. Send a few messages in the `kafka-console-producer` terminal to generate more traffic on the tenant.
+
As you send messages and the consumer receives them, they appear in the `kafka-console-consumer` terminal.
+
. In {astra-stream}, go to your tenant's **Namespaces and Topics** tab to inspect the activity in the `kafka` namespace.
To verify that your {kafka-short} messages are being produced and consumed in your {astra-stream} {pulsar-short} cluster, check the **Data In** metrics.
The number of messages should be equal to the number of messages you sent with the `kafka-console-producer`.
+
. To exit the producer and consumer shells, press kbd:[Ctrl]+kbd:[C] in each terminal.

Java client::
+
The following example uses a Java program to create a connection between {kafka-short} and your {astra-stream} tenant, configures a producer and consumer, and then sends a message.
This example uses Maven, but you can also use Gradle.
+
. Enable {product} and get the `ssl.properties` connection details, as explained in <<establish-the-kafka-protocol-handler>>.
+
. Create a new Maven project:
+
[source,shell]
----
mvn archetype:generate \
    -DgroupId=org.example \
    -DartifactId=StarlightForKafkaClient \
    -DarchetypeArtifactId=maven-archetype-quickstart \
    -DinteractiveMode=false
----
+
. Change to the new project directory:
+
[source,shell]
----
cd StarlightForKafkaClient
----
+
. Add the {kafka-short} client dependency to the `pom.xml` file:
+
.pom.xml
[source,xml]
----
    <dependency>
      <groupId>org.apache.kafka</groupId>
      <artifactId>kafka-clients</artifactId>
      <version>3.3.1</version>
    </dependency>
----
+
. Open the `App.java` file at `src/main/java/org/example/App.java`, and then delete any preexisting code in this file.
In the next steps, you will add code to this file to create a complete program that produces and consumes messages.
+
. Paste the following code in the file, and then replace the placeholder values with the values from your `ssl.properties` file.
Your editor will report errors because this isn't a complete program yet.
+
./src/main/java/org/example/App.java
[source,java,subs="+quotes"]
----
package org.example;

import org.apache.kafka.clients.consumer.ConsumerConfig;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.clients.producer.*;
import org.apache.kafka.common.serialization.LongSerializer;
import org.apache.kafka.common.serialization.StringDeserializer;
import org.apache.kafka.common.serialization.StringSerializer;

import java.time.Duration;
import java.util.Collections;
import java.util.Properties;

public class App {
  private static String bootstrapServers = "**BOOTSTRAP_SERVER_URL**";
  private static String pulsarToken = "**PASSWORD**";
  private static String tenantName = "**USERNAME**";
  private static final String namespace = "kafka";
  private static final String topicName = "quickstart";
  private static final String topic = String.format("persistent://%s/%s/%s", tenantName,namespace,topicName);

  public static void main(String[] args) {
----
+
. Optional: Replace `quickstart` with another name for the topic that receives messages from the {kafka-short} producer.
If the topic doesn't exist, it is created it automatically when the producer sends the first message.
+
. Add the following code that builds the configuration for the producer and consumer:
+
./src/main/java/org/example/App.java
[source,java]
----
    Properties config = new Properties();
    config.put("bootstrap.servers",bootstrapServers);
    config.put("security.protocol","SASL_SSL");
    config.put("sasl.jaas.config", String.format("org.apache.kafka.common.security.plain.PlainLoginModule required username='%s' password='token:%s';", tenantName, pulsarToken));
    config.put("sasl.mechanism","PLAIN");
    config.put("session.timeout.ms","45000");
    config.put(ProducerConfig.KEY_SERIALIZER_CLASS_CONFIG, LongSerializer.class.getName());
    config.put(ProducerConfig.VALUE_SERIALIZER_CLASS_CONFIG, StringSerializer.class.getName());
    config.put(ConsumerConfig.KEY_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
    config.put(ConsumerConfig.VALUE_DESERIALIZER_CLASS_CONFIG, StringDeserializer.class.getName());
    config.put("group.id", "my-consumer-group");
----
+
. Add the producer code, which is a simple flow that sends a single message and awaits acknowledgment:
+
./src/main/java/org/example/App.java
[source,java]
----
    KafkaProducer<Long, String> producer = new KafkaProducer<>(config);

    final ProducerRecord<Long, String> producerRecord = new ProducerRecord<>(topic, System.currentTimeMillis(), "Hello World");
    producer.send(producerRecord, new Callback() {
      public void onCompletion(RecordMetadata metadata, Exception e) {
        if (e != null)
          System.out.println(String.format("Send failed for record, %s. \nRecord data: %s",e.getMessage(), producerRecord));
        else
          System.out.println("Successfully sent message");
      }
    });

    producer.flush();
    producer.close();
----
+
. Add the consumer code, which creates a basic subscription and retrieves the latest messages on the topic:
+
./src/main/java/org/example/App.java
[source,java]
----
    final KafkaConsumer<Integer, String> consumer = new KafkaConsumer<Integer, String>(config);

    consumer.subscribe(Collections.singletonList(topic));
    ConsumerRecords<Integer, String> consumerRecords = consumer.poll(Duration.ofMillis(5000));

    System.out.println(String.format("Found %d total record(s)", consumerRecords.count()));

    for (ConsumerRecord<Integer, String> consumerRecord : consumerRecords) {
      System.out.println(consumerRecord);
    }

    consumer.commitSync();
    consumer.close();
  }
}
----
+
. Save `App.java`, and then build and run the JAR file for the complete program:
+
[source,shell]
----
mvn clean package assembly:single
java -jar target/StarlightForKafkaClient-1.0-SNAPSHOT-jar-with-dependencies.jar
----
+
. Make sure the result shows that a message was produces and consumed:
+
[source,shell]
----
Successfully sent message

Found 1 total record(s)
ConsumerRecord(topic = persistent://my-tenant-007/my-namespace/my-topic, partition = 0, leaderEpoch = null, offset = 22, CreateTime = 1673545962124, serialized key size = 8, serialized value size = 11, headers = RecordHeaders(headers = [], isReadOnly = false), key =   xxxxx, value = Hello World)
----
+
. In {astra-stream}, go to your tenant's **Namespaces and Topics** tab to inspect the activity in the `kafka` namespace.
+
If you everything was configured correctly, then the `kafka` namespace should have a topic named `quickstart` that was created by the Java program.
Additionally, the namespace's metrics should reflect that at least one message was published and consumed by your {astra-stream} {pulsar-short} topic.
====
--

{luna-streaming}::
+
--
To use the {kafka-short} CLI or a {kafka-short} client with {product}, you use your {luna-streaming} tenant as the {kafka-short} bootstrap server.
The following example command line tools included with the https://kafka.apache.org/downloads[{kafka} tarball], and it connects on `localhost:9092` because port forwarding was enabled in <<establish-the-kafka-protocol-handler>>.

. In your {kafka-short} installation directory, start the `kafka-console-producer` shell:
+
[source,shell]
----
bin/kafka-console-producer.sh \
--topic quickstart \
--bootstrap-server localhost:9092
----
+
You can replace `quickstart` with any other name for the topic that will receive messages from the producer.
If the specified topic doesn't exist in your {luna-streaming} tenant, it is created automatically when the producer sends the first message.
You can configure this behavior and other xref:starlight-for-kafka:configuration:starlight-kafka-configuration.adoc[{product} parameters] in the xref:installation:attachment$values.yaml[Helm chart].
+
To connect to a remote {luna-streaming} cluster, provide the full topic name and the bootstrap server URL for your {luna-streaming} tenant:
+
[source,shell,subs="+quotes"]
----
bin/kafka-console-producer.sh --topic "**TENANT_NAME**/**NAMESPACE_NAME**/**TOPIC_NAME**" --bootstrap-server "**SERVICE_URL**"
----

. When the producer is ready, type a message, and then press kbd:[Return] to send it.
Optionally, you can send several messages before starting the consumer to see how it retrieves past messages.

. In a new terminal window, start the `kafka-console-consumer` shell:
+
[source,shell]
----
bin/kafka-console-consumer.sh \
--topic quickstart \
--bootstrap-server localhost:9092 \
--from-beginning
----
+
Because this command uses the `--from-beginning` option, when the consumer starts, it retrieves any messages that were sent to the topic before it started.

. Send a few messages in the `kafka-console-producer` terminal to generate more traffic on the tenant.
+
As you send messages and the consumer receives them, they appear in the `kafka-console-consumer` terminal.

. Use the {pulsar-short} Admin CLI or the {luna-streaming} Admin Console to inspect your tenant's activity, and verify that messages were published and consumed on the specified topic.

. To exit the producer and consumer shells, press kbd:[Ctrl]+kbd:[C] in each terminal.
--

Self-managed::
+
--
To use the {kafka-short} CLI or a {kafka-short} client with {product}, you use your {pulsar-short} tenant as the {kafka-short} bootstrap server.
The following example command line tools included with the https://kafka.apache.org/downloads[{kafka} tarball], and it assumes port forwarding is enabled to connect on `localhost:9092`.

. Restart your {pulsar-short} brokers if you haven't done so already.

. In your {kafka-short} installation directory, start the `kafka-console-producer` shell:
+
[source,shell]
----
bin/kafka-console-producer.sh \
--topic quickstart \
--bootstrap-server localhost:9092
----
+
You can replace `quickstart` with any other name for the topic that will receive messages from the producer.
If the specified topic doesn't exist in your {pulsar-short} tenant, it is created automatically when the producer sends the first message.
You can configure this behavior and other xref:starlight-for-kafka:configuration:starlight-kafka-configuration.adoc[{product} parameters].
+
To connect to a remote {pulsar-short} cluster, provide the full topic name and the bootstrap server URL for your tenant:
+
[source,shell,subs="+quotes"]
----
bin/kafka-console-producer.sh --topic "**TENANT_NAME**/**NAMESPACE_NAME**/**TOPIC_NAME**" --bootstrap-server "**SERVICE_URL**"
----

. When the producer is ready, type a message, and then press kbd:[Return] to send it.
Optionally, you can send several messages before starting the consumer to see how it retrieves past messages.
+
You can also start the consumer first, and then start the producer afterwards.

. In a new terminal window, start the `kafka-console-consumer` shell:
+
[source,shell]
----
bin/kafka-console-consumer.sh \
--topic quickstart \
--bootstrap-server localhost:9092 \
--from-beginning
----
+
Because this command uses the `--from-beginning` option, when the consumer starts, it retrieves any messages that were sent to the topic before it started.
+
The `--bootstrap-server` is the address of your {pulsar-short} cluster where the {product} extension is installed.
Another way to format the localhost address is `PLAINTEXT://**IP_ADDRESS**:9092`.
+
Alternatively, you can create the consumer with the {pulsar-short} Client CLI.
For example, the following command creates a consumer on the `quickstart` topic with a subscription named `my-subscription`.
The `-n 0` option means the consumer continues running instead of closing the connection after consuming a message.
+
[source,bash]
----
pulsar-client consume quickstart -s "my-subscription" -n 0
----

. Send a few messages in the `kafka-console-producer` terminal to generate more traffic on the tenant.
+
As you send messages and the consumer receives them, they appear in the terminal where you started the consumer.

. Use the {pulsar-short} Admin CLI to inspect your tenant's activity, and verify that messages were published and consumed on the specified topic.

. To exit the producer and consumer shells, press kbd:[Ctrl]+kbd:[C] in each terminal.
--
======

== Next steps

Learn how to xref:configuration:starlight-kafka-configuration.adoc[configure and manage {product}].