= Install the {product} extension
:navtitle: Installation

This guide helps you get started producing and consuming {kafka-short} messages on a {pulsar-short} cluster.

This guide is focused on installing the extension into an existing {pulsar-short} cluster.

To install {product} as a proxy extension, see xref:operations:starlight-kafka-proxy.adoc[].

[#prerequisites]
== Prerequisites

{product} requires the following {pulsar-short} versions and {kafka-short} clients.

[cols=3]
|===
|{product} version |Compatible {pulsar-short} version |Supported {kafka-short} client

| 2.10 | 2.10.x | 0.10, 1.x, 2.x, 3.x
| 2.8  | 2.8.x  | 0.10, 1.x, 2.x, 3.x

|===

{product} supports all major {kafka-short} clients (0.10, 1.x, 2.x, 3.x).

{product} supports {kafka-short} Streams and the {kafka-short} CLI.

{product} requires JDK 11.

[#download]
== Download

. If this is the first time you've used protocol handlers with your {pulsar-short} deployment, create a `protocols` folder in the root of your {pulsar-short} directory.
. Download the `pulsar-protocol-handler-kafka-**VERSION**.nar` from the https://github.com/datastax/starlight-for-kafka/releases[{product} GitHub repository].
. Copy the `.nar` file to your `{pulsar-short}/protocols` directory.
. Proceed to xref:starlight-kafka-quickstart.adoc#configure[Configure protocol handler].

[#build]
== Build {product} protocol handler from source (optional)

If you prefer, build the protocol handler `.nar` from source.

. Clone the {product} GitHub repository to your local machine:
+
[source,bash]
----
git clone https://github.com/datastax/starlight-for-kafka.git
----

. Change to the local repository directory:
+
[source,bash]
----
cd starlight-for-kafka
----

. If needed, set `jenv global 11` to use JDK 11 because {product} requires JDK11.

. Build the Maven project:
+
[source,java]
----
mvn clean install -DskipTests
----

. If this is the first time you've used protocol handlers with your {pulsar-short} deployment, create a `protocols` folder in the root of your {pulsar-short} directory.

. Copy the protocol handler `.nar` file to your {pulsar-short} `protocols` directory.
After building the project, the `.nar` file is available at `starlight-for-kafka/kafka-impl/target/pulsar-protocol-handler-kafka-**VERSION**.nar`.

. Continue with xref:starlight-kafka-quickstart.adoc#configure[Configure protocol handler].

[#configure]
== Configure protocol handler

Configure the {pulsar-short} broker to run the {product} protocol handler as a plugin by adding configurations in the {pulsar-short} configuration file `broker.conf`.

[TIP]
====
Modify `standalone.conf` if you're running {pulsar-short} standalone.
====

. Add these configuration values to `broker.conf`:
+
[source,conf]
----
messagingProtocols=kafka
protocolHandlerDirectory=./protocols
allowAutoTopicCreationType=partitioned
----
+
[cols=3]
|===
|Property |Default Value |Suggested Value

|`messagingProtocols`
|
|`kafka`

|`protocolHandlerDirectory`
| `./protocols`
|Location of {product} `.nar` file

|`allowAutoTopicCreationType`
|`non-partitioned`
|`partitioned`

|===
+
[IMPORTANT]
====
`allowAutoTopicCreationType` is set to `non-partitioned` by default.
Since topics are partitioned by default in {kafka-short}, it's better to avoid creating non-partitioned topics unless {kafka-short} clients need to interact with existing non-partitioned topics.
====

. Set {kafka-short} listeners. `kafkaListeners` is a comma-separated list of listeners, and the host/IP and port which {kafka-short} binds to for listening.
+
[source,conf]
----
kafkaListeners=PLAINTEXT://127.0.0.1:9092
----

. Set {kafka-short} advertised listeners. `kafkaAdvertisedListeners` is a comma-separated list of listeners with their host/IP and port.
+
`kafkaAdvertisedListeners` isn't required unless you want to expose another address to the {kafka-short} client. It defaults to the same address as `kafkaListeners` by default.
+
[source,conf]
----
kafkaAdvertisedListeners=PLAINTEXT://127.0.0.1:9092
----

. Set offset management. Offset management is *required* because {product} depends upon {pulsar-short} broker-level entry metadata.
+
[source,conf]
----
brokerEntryMetadataInterceptors=org.apache.pulsar.common.intercept.AppendIndexMetadataInterceptor
----

. Disable the deletion of inactive topics:
+
[source,conf]
----
brokerDeleteInactiveTopicsEnabled=false
----
+
[IMPORTANT]
====
This isn't required but it is critical in {product}.

By default, {pulsar-short} deletes inactive partitions of a partitioned topic, but the metadata of the partitioned topic isn't deleted.

{product} cannot http://pulsar.apache.org/docs/en/admin-api-topics/#create-missed-partitions[create missed partitions] if `brokerDeleteInactiveTopicsEnabled` is set to `true`.
====

=== Additional configurations

* Set both retention *and* time to live policies http://pulsar.apache.org/docs/en/cookbooks-retention-expiry/[TTL] for {product} namespaces. If you only configure retention *without* configuring TTL, all messages on {product} topics cannot be deleted because {product} doesn't update a durable cursor.

* If a {pulsar-short} consumer and a {kafka-short} consumer both subscribe to the same topic with the same subscription (or group) name, the two consumers consume messages independently and they don't share the same subscription, even though the subscription name of a {pulsar-short} client is the same with the group name of a {kafka-short} client.

* {product} supports interaction between {pulsar-short} client and {kafka-short} client by default. If your topic is used only by the {pulsar-short} client or only by the {kafka-short} client, you can set `entryFormat=kafka` in `broker.conf` for better performance.

[#test]
== Test

After you have installed the {product} protocol handler and modified the {pulsar-short} broker configuration, verify your {product} deployment works by running a {kafka-short} client and consuming the messages on {pulsar-short}.

. Restart your {pulsar-short} brokers.

. Download https://kafka.apache.org/downloads[{kafka-short} 3.0.0] and untar the release package.
+
[source,bash]
----
tar -xzf kafka-3.0.0.tgz
cd kafka-3.0.0
----

. Run the {kafka-short} command-line consumer to listen for messages from the server. Here we're using localhost and {pulsar-short} standalone.
+
[source,bash]
----
bin/kafka-console-consumer.sh --bootstrap-server PLAINTEXT://127.0.0.1:9092 --topic test --from-beginning
----

. Create a consumer on {pulsar-short} to consume messages. Here we're adding `-n 0` to tell {pulsar-short} to continue running instead of closing the connection after consuming a message.
+
[source,bash]
----
pulsar-client consume test -s "my-subscription" -n 0
----

. Run the {kafka-short} command-line producer to send messages to the server, and send a message.
+
[source,console]
----
bin/kafka-console-producer.sh --bootstrap-server PLAINTEXT://127.0.0.1:9092 --topic test
>hi pulsar, it's me, kafka!
----

. If {product} is working, your message appears on your {pulsar-short} consumer:
+
[source,console]
----
----- got message -----
key:[null], properties:[], content:hi pulsar, it's me, kafka!
----

== Next steps

Learn how to xref:configuration:starlight-kafka-configuration.adoc[configure and manage {product}].